name: Acceptance
on:
  pull_request:
    branches:
    - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches:
    - master
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install Terraform
      run: |
        set -eu
        curl -s -L "https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip" > "terraform-bin.zip"

        bin_dir="$GITHUB_WORKSPACE/bin"
        terraform_bin="$bin_dir/terraform"
        new_path="PATH=$bin_dir:$PATH"
        echo "$new_path" >> $GITHUB_ENV
        echo "Set env: $new_path"

        mkdir -p "$bin_dir"
        unzip -p "terraform-bin.zip" > "$terraform_bin"
        chmod +x "$terraform_bin"
        rm "terraform-bin.zip"

        echo "Installed: $(eval "$terraform_bin version") ($terraform_bin)"

    - uses: actions/checkout@master

    - name: Run make fmt
      if: runner.os != 'Windows'
      run: |
        make fmt
        git diff --exit-code; code=$?; git checkout -- .; (exit $code)

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: |
        echo "Using: $(terraform version) ($(which terraform))"
        make testacc TEST="./heroku/"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_ORGANIZATION: terraform-ci-test-team
        HEROKU_SPACES_ORGANIZATION: terraform-ci-test-team
        HEROKU_TEAM: terraform-ci-test-team
        HEROKU_EMAIL: mars+heroku-terraform-ci@heroku.com
        HEROKU_TEST_USER: mars+heroku-terraform-ci-admin@heroku.com
        HEROKU_NON_ADMIN_TEST_USER: mars+heroku-terraform-ci-member@heroku.com
        HEROKU_SLUG_ID: 8527dbf3-c0a0-4255-beab-aca0aad1dfc9
        HEROKU_USER_ID: 007fa6e2-00a1-429e-92a0-7bbe14b063fc
#        GOFLAGS: "-mod=vendor"
        # TF_LOG: DEBUG
