name: Acceptance
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
# Skip nightly runs, at least until the org's GitHub Actions budget problem is resolved.
#   schedule:
#     # Three-hours after midnight Pacific
#     - cron: "0 11 * * *"

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@master

    - name: Run make fmt
      if: runner.os != 'Windows'
      run: |
        make fmt
        git diff --exit-code; code=$?; git checkout -- .; (exit $code)

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: |
        make testacc TEST="./heroku/"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_ORGANIZATION: terraform-ci-test-team
        HEROKU_SPACES_ORGANIZATION: terraform-ci-test-team
        HEROKU_TEAM: terraform-ci-test-team
        HEROKU_EMAIL: mars+heroku-terraform-ci@heroku.com
        HEROKU_TEST_USER: mars+heroku-terraform-ci-admin@heroku.com
        HEROKU_NON_ADMIN_TEST_USER: mars+heroku-terraform-ci-member@heroku.com
        HEROKU_SLUG_ID: 8527dbf3-c0a0-4255-beab-aca0aad1dfc9
        HEROKU_USER_ID: 007fa6e2-00a1-429e-92a0-7bbe14b063fc
#        GOFLAGS: "-mod=vendor"
        # TF_LOG: DEBUG
